# Generated by Django 2.2.5 on 2019-10-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_abc_qqq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='qqq',
        ),
    ]
